import type {
  AnalysisFormValues,
  ActivityPoint,
  DashboardResult,
  PipelineStage,
  SourceMode,
} from "../types/analysis";
import type { Locale } from "../i18n";

export const defaultFormValues: AnalysisFormValues = {
  sourceMode: "url",
  url: "",
  html: "",
  recordsJson: "",
  recordsFileName: "",
  sourceUrl: "",
  analysisDepth: "standard",
  waitMs: "",
};

export const PIPELINE_STAGE_COUNT = 5;

const DEMO_ACTIVITY_SERIES_RU: ActivityPoint[] = [
  { label: "дек. 2024", reviews: 52, suspicious: 3, bucketStart: "2024-12-01T00:00:00.000Z", bucketEnd: "2024-12-31T23:59:59.999Z" },
  { label: "янв. 2025", reviews: 61, suspicious: 4, bucketStart: "2025-01-01T00:00:00.000Z", bucketEnd: "2025-01-31T23:59:59.999Z" },
  { label: "фев. 2025", reviews: 70, suspicious: 5, bucketStart: "2025-02-01T00:00:00.000Z", bucketEnd: "2025-02-28T23:59:59.999Z" },
  { label: "мар. 2025", reviews: 82, suspicious: 7, bucketStart: "2025-03-01T00:00:00.000Z", bucketEnd: "2025-03-31T23:59:59.999Z" },
  { label: "апр. 2025", reviews: 96, suspicious: 10, bucketStart: "2025-04-01T00:00:00.000Z", bucketEnd: "2025-04-30T23:59:59.999Z" },
  { label: "май 2025", reviews: 104, suspicious: 14, bucketStart: "2025-05-01T00:00:00.000Z", bucketEnd: "2025-05-31T23:59:59.999Z" },
  { label: "июнь 2025", reviews: 120, suspicious: 18, bucketStart: "2025-06-01T00:00:00.000Z", bucketEnd: "2025-06-30T23:59:59.999Z" },
  { label: "июль 2025", reviews: 138, suspicious: 27, bucketStart: "2025-07-01T00:00:00.000Z", bucketEnd: "2025-07-31T23:59:59.999Z" },
  { label: "авг. 2025", reviews: 154, suspicious: 35, bucketStart: "2025-08-01T00:00:00.000Z", bucketEnd: "2025-08-31T23:59:59.999Z" },
  { label: "сент. 2025", reviews: 180, suspicious: 52, bucketStart: "2025-09-01T00:00:00.000Z", bucketEnd: "2025-09-30T23:59:59.999Z" },
  { label: "окт. 2025", reviews: 190, suspicious: 60, bucketStart: "2025-10-01T00:00:00.000Z", bucketEnd: "2025-10-31T23:59:59.999Z" },
  { label: "нояб. 2025", reviews: 168, suspicious: 48, bucketStart: "2025-11-01T00:00:00.000Z", bucketEnd: "2025-11-30T23:59:59.999Z" },
  { label: "дек. 2025", reviews: 142, suspicious: 36, bucketStart: "2025-12-01T00:00:00.000Z", bucketEnd: "2025-12-31T23:59:59.999Z" },
  { label: "янв. 2026", reviews: 128, suspicious: 30, bucketStart: "2026-01-01T00:00:00.000Z", bucketEnd: "2026-01-31T23:59:59.999Z" },
  { label: "фев. 2026", reviews: 110, suspicious: 24, bucketStart: "2026-02-01T00:00:00.000Z", bucketEnd: "2026-02-28T23:59:59.999Z" },
  { label: "мар. 2026", reviews: 92, suspicious: 20, bucketStart: "2026-03-01T00:00:00.000Z", bucketEnd: "2026-03-31T23:59:59.999Z" },
  { label: "апр. 2026", reviews: 84, suspicious: 16, bucketStart: "2026-04-01T00:00:00.000Z", bucketEnd: "2026-04-30T23:59:59.999Z" },
  { label: "май 2026", reviews: 69, suspicious: 9, bucketStart: "2026-05-01T00:00:00.000Z", bucketEnd: "2026-05-31T23:59:59.999Z" },
];

const DEMO_ACTIVITY_SERIES_EN: ActivityPoint[] = [
  { label: "Dec 2024", reviews: 52, suspicious: 3, bucketStart: "2024-12-01T00:00:00.000Z", bucketEnd: "2024-12-31T23:59:59.999Z" },
  { label: "Jan 2025", reviews: 61, suspicious: 4, bucketStart: "2025-01-01T00:00:00.000Z", bucketEnd: "2025-01-31T23:59:59.999Z" },
  { label: "Feb 2025", reviews: 70, suspicious: 5, bucketStart: "2025-02-01T00:00:00.000Z", bucketEnd: "2025-02-28T23:59:59.999Z" },
  { label: "Mar 2025", reviews: 82, suspicious: 7, bucketStart: "2025-03-01T00:00:00.000Z", bucketEnd: "2025-03-31T23:59:59.999Z" },
  { label: "Apr 2025", reviews: 96, suspicious: 10, bucketStart: "2025-04-01T00:00:00.000Z", bucketEnd: "2025-04-30T23:59:59.999Z" },
  { label: "May 2025", reviews: 104, suspicious: 14, bucketStart: "2025-05-01T00:00:00.000Z", bucketEnd: "2025-05-31T23:59:59.999Z" },
  { label: "Jun 2025", reviews: 120, suspicious: 18, bucketStart: "2025-06-01T00:00:00.000Z", bucketEnd: "2025-06-30T23:59:59.999Z" },
  { label: "Jul 2025", reviews: 138, suspicious: 27, bucketStart: "2025-07-01T00:00:00.000Z", bucketEnd: "2025-07-31T23:59:59.999Z" },
  { label: "Aug 2025", reviews: 154, suspicious: 35, bucketStart: "2025-08-01T00:00:00.000Z", bucketEnd: "2025-08-31T23:59:59.999Z" },
  { label: "Sep 2025", reviews: 180, suspicious: 52, bucketStart: "2025-09-01T00:00:00.000Z", bucketEnd: "2025-09-30T23:59:59.999Z" },
  { label: "Oct 2025", reviews: 190, suspicious: 60, bucketStart: "2025-10-01T00:00:00.000Z", bucketEnd: "2025-10-31T23:59:59.999Z" },
  { label: "Nov 2025", reviews: 168, suspicious: 48, bucketStart: "2025-11-01T00:00:00.000Z", bucketEnd: "2025-11-30T23:59:59.999Z" },
  { label: "Dec 2025", reviews: 142, suspicious: 36, bucketStart: "2025-12-01T00:00:00.000Z", bucketEnd: "2025-12-31T23:59:59.999Z" },
  { label: "Jan 2026", reviews: 128, suspicious: 30, bucketStart: "2026-01-01T00:00:00.000Z", bucketEnd: "2026-01-31T23:59:59.999Z" },
  { label: "Feb 2026", reviews: 110, suspicious: 24, bucketStart: "2026-02-01T00:00:00.000Z", bucketEnd: "2026-02-28T23:59:59.999Z" },
  { label: "Mar 2026", reviews: 92, suspicious: 20, bucketStart: "2026-03-01T00:00:00.000Z", bucketEnd: "2026-03-31T23:59:59.999Z" },
  { label: "Apr 2026", reviews: 84, suspicious: 16, bucketStart: "2026-04-01T00:00:00.000Z", bucketEnd: "2026-04-30T23:59:59.999Z" },
  { label: "May 2026", reviews: 69, suspicious: 9, bucketStart: "2026-05-01T00:00:00.000Z", bucketEnd: "2026-05-31T23:59:59.999Z" },
];

export function getBasePipelineStages(locale: Locale): PipelineStage[] {
  return locale === "ru"
    ? [
        {
          key: "collect",
          label: "Сбор страницы",
          description: "Получаем страницу товара или загружаем переданный источник.",
          state: "pending",
        },
        {
          key: "extract",
          label: "Извлечение отзывов",
          description: "Разбираем HTML и приводим блоки с отзывами к единому формату.",
          state: "pending",
        },
        {
          key: "features",
          label: "Построение признаков",
          description: "Генерируем текстовые, временные и поведенческие сигналы риска.",
          state: "pending",
        },
        {
          key: "analyze",
          label: "Запуск модели",
          description: "Применяем ML и поиск аномалий ко всему набору отзывов.",
          state: "pending",
        },
        {
          key: "profile",
          label: "Риск-профиль",
          description: "Собираем финальное объяснение и отчет для ручной проверки.",
          state: "pending",
        },
      ]
    : [
        {
          key: "collect",
          label: "Collect page",
          description: "Fetching the product page or loading the provided source.",
          state: "pending",
        },
        {
          key: "extract",
          label: "Extract reviews",
          description: "Parsing the HTML and normalizing review blocks.",
          state: "pending",
        },
        {
          key: "features",
          label: "Build features",
          description: "Generating NLP, temporal, and behavioral fraud signals.",
          state: "pending",
        },
        {
          key: "analyze",
          label: "Run model",
          description: "Applying ML and anomaly detection across the review set.",
          state: "pending",
        },
        {
          key: "profile",
          label: "Risk profile",
          description: "Building the final explanation and moderation dashboard.",
          state: "pending",
        },
      ];
}

function getHeroPreviewResult(locale: Locale): DashboardResult {
  return locale === "ru"
    ? {
        sourceMode: "url",
        overview: {
          productName: "TEMOFON Cork Footbed Sandals",
          sourceLabel: "amazon.com",
          statusLabel: "Повышенный риск",
          riskScore: 82,
          manipulationProbability: 76,
          confidence: 94,
          reviewCount: 2040,
          suspiciousCount: 418,
          manualReviewCount: 226,
          verdict:
            "Текущая выборка отзывов показывает сочетание текстовых шаблонов, временного всплеска публикаций, повторяющихся фото, слабых доказательств использования товара и сдвига рейтингового поведения у партнерской страницы.",
        },
        trustBreakdown: [
          { name: "Надежные", value: 1396, fill: "#0f766e" },
          { name: "Подозрительные", value: 418, fill: "#c35e43" },
          { name: "Неопределенные", value: 226, fill: "#c4872f" },
        ],
        activitySeries: DEMO_ACTIVITY_SERIES_RU,
        anomalyTypes: [
          { type: "Текстовая схожесть", count: 146 },
          { type: "Всплеск публикаций", count: 118 },
          { type: "Временная кластеризация", count: 104 },
          { type: "Повтор фото покупателей", count: 91 },
          { type: "Слабая конкретика в отзыве", count: 84 },
          { type: "Смешанный русско-английский язык", count: 73 },
          { type: "Проверка на AI", count: 68 },
          { type: "Сдвиг рейтингов", count: 64 },
          { type: "Повтор тональных шаблонов", count: 58 },
          { type: "Фото vs текст отзыва", count: 57 },
          { type: "OCR текста на фото", count: 52 },
          { type: "Авторский кластер", count: 46 },
          { type: "Временной кластер фото", count: 44 },
          { type: "Стоковые/маркетинговые фото", count: 38 },
          { type: "Признаки синтетического изображения", count: 21 },
        ],
        detectorCards: [
          {
            id: "text-similarity",
            name: "Пик текстовой схожести",
            description: "Несколько отзывов используют почти одинаковые формулировки и промо-тон.",
            severity: "high",
            score: 82,
            status: "critical",
          },
          {
            id: "weak-product-evidence",
            name: "Слабая конкретика в отзыве",
            description: "Отделяет реальные детали использования от общих фраз про цену, доставку, упаковку и качество без проверяемого опыта.",
            severity: "medium",
            score: 66,
            status: "watch",
          },
          {
            id: "ai-text-review-risk",
            name: "Проверка на AI",
            description: "Оценивает признаки машинно выверенной подачи: ровный рекламный ритм, повторяемые речевые связки и нехватку проверяемых деталей покупки.",
            severity: "medium",
            score: 69,
            status: "watch",
          },
          {
            id: "burst-posting",
            name: "Паттерн всплеска публикаций",
            description: "Плотный блок отзывов появился в очень коротком временном окне.",
            severity: "high",
            score: 76,
            status: "critical",
          },
          {
            id: "reviewer-trust",
            name: "Аномалия доверия к авторам",
            description: "Часть видимых авторов дает непропорционально много отзывов.",
            severity: "medium",
            score: 63,
            status: "watch",
          },
          {
            id: "rating-distribution",
            name: "Сдвиг распределения рейтингов",
            description: "В последнем кластере видимых отзывов доминируют экстремально позитивные оценки.",
            severity: "medium",
            score: 58,
            status: "watch",
          },
          {
            id: "sentiment-repetition",
            name: "Повтор тональных шаблонов",
            description: "Тональность повторяет один и тот же эмоциональный шаблон у разных авторов.",
            severity: "medium",
            score: 61,
            status: "watch",
          },
          {
            id: "bilingual-slang",
            name: "Проверка смешанного русско-английского языка",
            description: "Смешанный русско-английский язык выглядит как рекламный шаблон, а не как естественные детали покупателя.",
            severity: "medium",
            score: 59,
            status: "watch",
          },
          {
            id: "customer-photo-reuse",
            name: "Дубликаты фото покупателей",
            description: "Два отзыва переиспользуют одно и то же покупательское фото с разными CDN-параметрами.",
            severity: "medium",
            score: 64,
            status: "watch",
          },
          {
            id: "timed-photo-cluster",
            name: "Временной кластер фото",
            description: "Одно и то же фото появляется у разных авторов в коротком окне, что похоже на скоординированную кампанию.",
            severity: "high",
            score: 72,
            status: "watch",
          },
          {
            id: "image-text-alignment",
            name: "Фото vs текст отзыва",
            description: "Модель сходства изображений помечает фото, которые слабо совпадают с текстом отзыва и категорией товара.",
            severity: "medium",
            score: 67,
            status: "watch",
          },
          {
            id: "stock-marketing-photo",
            name: "Стоковые/маркетинговые фото",
            description: "Один из фото-сигналов похож на каталожный или студийный материал вместо покупательского снимка.",
            severity: "medium",
            score: 62,
            status: "watch",
          },
          {
            id: "ai-synthetic-image",
            name: "Признаки синтетического изображения",
            description: "Слабая подсказка по синтетическим признакам; не используется как самостоятельное доказательство.",
            severity: "low",
            score: 41,
            status: "stable",
          },
          {
            id: "image-ocr-text",
            name: "OCR текста на фото",
            description: "На фото найден текст распродажи, водяной знак или текст маркетплейса, не похожий на обычный покупательский снимок.",
            severity: "medium",
            score: 57,
            status: "watch",
          },
          {
            id: "temporal-clustering",
            name: "Временная кластеризация",
            description: "Метки времени формируют короткие пики вместо органичного распределения отзывов.",
            severity: "high",
            score: 79,
            status: "critical",
          },
        ],
        explainability: [
          {
            label: "Высокая текстовая схожесть между отзывами",
            weight: 0.25,
            narrative: "Модель нашла повторяющиеся лексические структуры и почти дублирующиеся фразы у нескольких авторов.",
          },
          {
            label: "Всплеск отзывов в коротком интервале",
            weight: 0.2,
            narrative: "Активность публикаций сжата в узкий временной диапазон, что нетипично для органической обратной связи.",
          },
          {
            label: "Фото, OCR и повтор изображений",
            weight: 0.18,
            narrative: "Повтор фото, текст распродажи на снимках и каталожные изображения усиливают сигнал координации.",
          },
          {
            label: "Проверка на AI",
            weight: 0.14,
            narrative:
              "Детектор учитывает машинно выверенный ритм, длинное тире, клише доставки/упаковки/цены и нехватку проверяемых деталей.",
          },
          {
            label: "Низкая устойчивость reviewer trust",
            weight: 0.13,
            narrative: "Поведение видимых авторов выглядит более концентрированным и менее разнообразным, чем ожидается для здоровой страницы товара.",
          },
          {
            label: "Дрейф распределения рейтингов",
            weight: 0.1,
            narrative: "Недавние оценки слишком сильно тяготеют к экстремальным значениям, что усиливает риск манипуляции.",
          },
        ],
        suspiciousReviews: [
          {
            id: "rvw-001",
            title: "Цена и сервис приятно удивили",
            text: "Цена адекватная — не жалко платить за результат. Доставка/поддержка/упаковка — приятно удивили. В целом товар оставил ровное положительное впечатление, рекомендую к покупке.",
            rating: 5,
            suspiciousness: 0.96,
            reason: "Промо-язык, шаблонный текст и повтор фото",
            author: "TopPick247",
            authorTrust: "low",
            date: "2026-04-13",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["цена адекватная", "не жалко платить", "доставка/поддержка/упаковка", "приятно удивили", "рекомендую к покупке"],
            languageSignalScore: 0.91,
            languageAuthenticityScore: 0.1,
            languageDomain: "одежда",
            templateClustered: true,
            uncertaintyScore: 0.1,
            oodScore: 0.09,
            imageUrls: ["https://cdn.example.test/reviews/sandal-fit-42.jpg?w=640&q=80"],
            imageCount: 1,
            duplicateImageCount: 1,
            duplicateImageClusterSize: 4,
            duplicateImageScore: 0.87,
            duplicateImageFlag: true,
            imageTemporalClusterScore: 0.74,
            imageTemporalClusterFlag: true,
            imageTemporalClusterSize: 4,
            imageTemporalClusterAuthorCount: 4,
            imageTemporalClusterWindowHours: 36,
            imageTextAlignmentScore: 0.22,
            imageTextMismatchScore: 0.76,
            imageTextMismatchFlag: true,
            imageTextAlignmentLabel: "strong_mismatch",
            imageStockMarketingScore: 0.71,
            imageStockMarketingFlag: true,
            imageStockMarketingLabel: "stock_catalog",
            imageSyntheticScore: 0.58,
            imageSyntheticFlag: true,
            imageSyntheticLabel: "weak_synthetic_hint",
            imageOcrScore: 0.66,
            imageOcrFlag: true,
            imageOcrText: "SALE BEST PRODUCT Amazon official store",
            imageOcrLabels: ["sale_discount", "hype_claim", "foreign_marketplace_watermark"],
            aiTextScore: 0.78,
            aiTextFlag: true,
            aiTextLabel: "likely_ai_text",
            aiTextReasons: [
              "Детектор отметил признаки синтетической подачи текста; это сигнал для модерации, а не доказательство.",
              "Пунктуационный рисунок с длинным тире усиливает сигнал машинно выверенной стилистики.",
              "Отзыв использует компактные маркетплейс-клише про цену, доставку, поддержку или упаковку с синтетическим ритмом подачи.",
            ],
          },
          {
            id: "rvw-002",
            title: "Пять звезд без сомнений",
            text: "Цена адекватная — результат чувствуется сразу. Доставка/поддержка/упаковка — всё приятно удивило, качество безупречное, 100 процентов рекомендую всем.",
            rating: 5,
            suspiciousness: 0.91,
            reason: "Повтор sentiment-а и публикация в burst-кластере",
            author: "dailydeal_mira",
            authorTrust: "low",
            date: "2026-04-13",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["цена адекватная", "результат чувствуется сразу", "доставка/поддержка/упаковка", "приятно удивило"],
            languageSignalScore: 0.84,
            languageAuthenticityScore: 0.17,
            languageDomain: "одежда",
            templateClustered: true,
            uncertaintyScore: 0.2,
            oodScore: 0.14,
            imageUrls: ["https://cdn.example.test/reviews/sandal-fit-42.jpg?w=320&q=70"],
            imageCount: 1,
            duplicateImageCount: 1,
            duplicateImageClusterSize: 4,
            duplicateImageScore: 0.87,
            duplicateImageFlag: true,
            imageTemporalClusterScore: 0.74,
            imageTemporalClusterFlag: true,
            imageTemporalClusterSize: 4,
            imageTemporalClusterAuthorCount: 4,
            imageTemporalClusterWindowHours: 36,
            aiTextScore: 0.72,
            aiTextFlag: true,
            aiTextLabel: "ai_text_signal",
            aiTextReasons: [
              "Детектор отметил признаки синтетической подачи текста; это сигнал для модерации, а не доказательство.",
              "Отзыв использует компактные маркетплейс-клише про цену, доставку, поддержку или упаковку с синтетическим ритмом подачи.",
            ],
          },
          {
            id: "rvw-003",
            title: "Одинаковые плюсы без деталей",
            text: "Хорошие сандалии, хорошая посадка, хорошее качество, хороший комфорт, хороший материал, в целом хороший товар.",
            rating: 5,
            suspiciousness: 0.83,
            reason: "Низкое лексическое разнообразие",
            author: "comfortshopper",
            authorTrust: "neutral",
            date: "2026-04-12",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["great", "good quality", "comfortable"],
            languageSignalScore: 0.49,
            languageAuthenticityScore: 0.42,
            languageDomain: "одежда",
            templateClustered: false,
            uncertaintyScore: 0.61,
            oodScore: 0.27,
            aiTextScore: 0.58,
            aiTextFlag: false,
            aiTextLabel: "weak_ai_text_hint",
            aiTextReasons: [
              "Текст слабо подкреплён проверяемыми деталями: покупкой, доставкой, размером или реальным сценарием использования.",
            ],
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-004",
            title: "Коротко, но идеально",
            text: "Идеально. Понравилось. Must buy.",
            rating: 5,
            suspiciousness: 0.77,
            reason: "Экстремальная оценка при слишком общей аргументации",
            author: "A1TopChoice",
            authorTrust: "low",
            date: "2026-04-10",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["must buy", "perfect"],
            languageSignalScore: 0.58,
            languageAuthenticityScore: 0.24,
            languageDomain: "одежда",
            templateClustered: false,
            uncertaintyScore: 0.62,
            oodScore: 0.31,
            imageUrls: ["https://cdn.example.test/reviews/sandal-box-single.jpg"],
            imageCount: 1,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            imageTextAlignmentScore: 0.34,
            imageTextMismatchScore: 0.46,
            imageTextMismatchFlag: false,
          },
          {
            id: "rvw-005",
            title: "Негативный всплеск после конфликта",
            text: "Все ужасно, товар развалился сразу, продавец плохой, никому не советую. Поддержка молчит, деньги потеряны.",
            rating: 1,
            suspiciousness: 0.86,
            reason: "Резкий негативный кластер и повтор формулировок",
            author: "angry_case_77",
            authorTrust: "low",
            date: "2026-04-13",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["никому не советую", "деньги потеряны", "продавец плохой", "same complaint"],
            languageSignalScore: 0.72,
            languageAuthenticityScore: 0.23,
            languageDomain: "одежда",
            templateClustered: true,
            uncertaintyScore: 0.34,
            oodScore: 0.18,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-006",
            title: "Фото выглядит как каталог",
            text: "Очень красивые сандалии, на фото видно идеальный товар, беру уже второй раз, всем советую этот магазин.",
            rating: 5,
            suspiciousness: 0.81,
            reason: "Стоковое фото и слабое совпадение с текстом",
            author: "style_market_pro",
            authorTrust: "neutral",
            date: "2026-04-12",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["идеальный товар", "всем советую", "catalog-like photo"],
            languageSignalScore: 0.55,
            languageAuthenticityScore: 0.31,
            languageDomain: "одежда",
            templateClustered: false,
            uncertaintyScore: 0.44,
            oodScore: 0.24,
            imageUrls: ["https://cdn.example.test/reviews/catalog-sandal-white-bg.jpg"],
            imageCount: 2,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0.18,
            duplicateImageFlag: false,
            imageTextAlignmentScore: 0.28,
            imageTextMismatchScore: 0.64,
            imageTextMismatchFlag: true,
            imageTextAlignmentLabel: "weak_alignment",
            imageStockMarketingScore: 0.83,
            imageStockMarketingFlag: true,
            imageStockMarketingLabel: "studio_catalog",
            imageSyntheticScore: 0.22,
            imageSyntheticFlag: false,
          },
          {
            id: "rvw-007",
            title: "Слишком похожий авторский профиль",
            text: "Покупал жене, размер подошел, доставка пришла нормально. Но отзыв похож на несколько соседних записей по структуре.",
            rating: 4,
            suspiciousness: 0.68,
            reason: "Повтор структуры автора и средняя неопределенность",
            author: "buyer_4421",
            authorTrust: "neutral",
            date: "2026-04-09",
            severity: "low",
            triageStatus: "needs_manual_review",
            languageProfile: "neutral",
            detectedTerms: ["same author pattern", "размер подошел"],
            languageSignalScore: 0.29,
            languageAuthenticityScore: 0.63,
            languageDomain: "одежда",
            templateClustered: false,
            uncertaintyScore: 0.57,
            oodScore: 0.19,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-008",
            title: "Нормальный отзыв для сравнения",
            text: "Носил сандалии две недели. Стелька мягкая, но ремешок сначала натирал. После регулировки стало удобнее.",
            rating: 4,
            suspiciousness: 0.24,
            reason: "Есть конкретные детали использования",
            author: "realwalk_samara",
            authorTrust: "trusted",
            date: "2026-04-07",
            severity: "low",
            triageStatus: "confident_clean",
            languageProfile: "organic",
            detectedTerms: ["две недели", "ремешок натирал", "после регулировки"],
            languageSignalScore: 0.12,
            languageAuthenticityScore: 0.82,
            languageDomain: "одежда",
            templateClustered: false,
            uncertaintyScore: 0.16,
            oodScore: 0.07,
            imageUrls: ["https://cdn.example.test/reviews/real-wear-detail.jpg"],
            imageCount: 1,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            imageTextAlignmentScore: 0.78,
            imageTextMismatchScore: 0.08,
            imageTextMismatchFlag: false,
          },
          {
            id: "rvw-009",
            title: "Один автор хвалит много товаров",
            text: "Заказывал у этого продавца уже пятый товар, все всегда идеально, доставка молниеносная, качество лучше всех.",
            rating: 5,
            suspiciousness: 0.79,
            reason: "Неестественная активность автора по нескольким товарам",
            author: "multi_item_boost",
            authorTrust: "low",
            date: "2026-04-12",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["пятый товар", "всегда идеально", "лучше всех", "multi-item pattern"],
            languageSignalScore: 0.52,
            languageAuthenticityScore: 0.35,
            languageDomain: "одежда",
            templateClustered: true,
            uncertaintyScore: 0.47,
            oodScore: 0.29,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-010",
            title: "Отзыв с OCR-водяным знаком",
            text: "Фото полностью показывает качество, магазин лучший, скидка супер, берите пока есть размеры.",
            rating: 5,
            suspiciousness: 0.84,
            reason: "Распознанный текст на фото и маркетинговый стиль",
            author: "sale_photo_user",
            authorTrust: "low",
            date: "2026-04-13",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["скидка супер", "лучший магазин", "OCR watermark", "sale banner"],
            languageSignalScore: 0.73,
            languageAuthenticityScore: 0.22,
            languageDomain: "одежда",
            templateClustered: true,
            uncertaintyScore: 0.31,
            oodScore: 0.21,
            imageUrls: ["https://cdn.example.test/reviews/sale-watermark-sandal.jpg"],
            imageCount: 1,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0.14,
            duplicateImageFlag: false,
            imageTextAlignmentScore: 0.32,
            imageTextMismatchScore: 0.59,
            imageTextMismatchFlag: true,
            imageTextAlignmentLabel: "weak_alignment",
            imageStockMarketingScore: 0.76,
            imageStockMarketingFlag: true,
            imageStockMarketingLabel: "marketing_banner",
            imageSyntheticScore: 0.31,
            imageSyntheticFlag: false,
            imageOcrScore: 0.88,
            imageOcrFlag: true,
            imageOcrText: "SUPER SALE -50% LIMITED OFFER",
            imageOcrLabels: ["discount_banner", "limited_offer", "watermark"],
          },
          {
            id: "rvw-011",
            title: "Слишком нейтральный шаблон",
            text: "Товар соответствует описанию, доставка нормальная, продавец общался нормально, в целом все нормально.",
            rating: 4,
            suspiciousness: 0.55,
            reason: "Повтор нейтрального шаблона без деталей опыта",
            author: "neutral_case_18",
            authorTrust: "neutral",
            date: "2026-04-08",
            severity: "low",
            triageStatus: "needs_manual_review",
            languageProfile: "neutral",
            detectedTerms: ["нормально", "соответствует описанию", "в целом все нормально"],
            languageSignalScore: 0.25,
            languageAuthenticityScore: 0.49,
            languageDomain: "одежда",
            templateClustered: true,
            uncertaintyScore: 0.52,
            oodScore: 0.16,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-012",
            title: "Детальный отзыв после использования",
            text: "Через месяц носки подошва не просела, но на правом ремешке появилась потертость. Размер 42 подошел на стопу 26,5 см.",
            rating: 4,
            suspiciousness: 0.18,
            reason: "Органичный отзыв с проверяемыми деталями",
            author: "verified_step_42",
            authorTrust: "trusted",
            date: "2026-04-05",
            severity: "low",
            triageStatus: "confident_clean",
            languageProfile: "organic",
            detectedTerms: ["месяц носки", "ремешок", "26,5 см"],
            languageSignalScore: 0.08,
            languageAuthenticityScore: 0.88,
            languageDomain: "одежда",
            templateClustered: false,
            uncertaintyScore: 0.12,
            oodScore: 0.05,
            imageUrls: ["https://cdn.example.test/reviews/wear-after-month.jpg"],
            imageCount: 1,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            imageTextAlignmentScore: 0.84,
            imageTextMismatchScore: 0.06,
            imageTextMismatchFlag: false,
          },
          {
            id: "rvw-013",
            title: "Короткий чистый отзыв",
            text: "Размер подошел, ремешок не натирает. Упаковка целая.",
            rating: 5,
            suspiciousness: 0.05,
            reason: "Короткий маркетплейс-отзыв с конкретными деталями без промо-шаблона",
            author: "size_fit_05",
            authorTrust: "trusted",
            date: "2026-04-04",
            severity: "low",
            triageStatus: "confident_clean",
            languageProfile: "organic",
            detectedTerms: ["размер подошел", "ремешок", "упаковка целая"],
            languageSignalScore: 0.07,
            languageAuthenticityScore: 0.76,
            languageDomain: "одежда",
            templateClustered: false,
            uncertaintyScore: 0.14,
            oodScore: 0.08,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            aiTextScore: 0.11,
            aiTextFlag: false,
            aiTextLabel: "marketplace_clean",
            aiTextReasons: [
              "Короткий текст содержит проверяемые детали покупки и не похож на рекламный шаблон.",
            ],
          },
        ],
        keyInsights: [
          "После спокойного периода обнаружен резкий всплеск отзывов с высокой долей подозрительных записей.",
          "Часть отзывов повторяет рекламные формулировки и смешивает русский/английский язык без конкретики использования.",
          "Проверка на AI показывает отдельный скор: учитывает машинно выверенную подачу, длинное тире, повторяемые связки и нехватку деталей покупки.",
          "Фото-сигналы показывают повтор изображений, распознанный текст распродажи и признаки каталожных материалов.",
          "Есть разные уровни triage: уверенно подозрительные, записи для ручной проверки и чистые примеры, включая короткий низкорисковый отзыв.",
        ],
      }
    : {
        sourceMode: "url",
        overview: {
          productName: "TEMOFON Cork Footbed Sandals",
          sourceLabel: "amazon.com",
          statusLabel: "Elevated risk",
          riskScore: 82,
          manipulationProbability: 76,
          confidence: 94,
          reviewCount: 2040,
          suspiciousCount: 418,
          manualReviewCount: 226,
          verdict:
            "The current partner-page sample combines repeated text templates, burst posting, reused customer photos, weak product evidence, and a visible shift in rating behavior.",
        },
        trustBreakdown: [
          { name: "Trustworthy", value: 1396, fill: "#0f766e" },
          { name: "Suspicious", value: 418, fill: "#c35e43" },
          { name: "Uncertain", value: 226, fill: "#c4872f" },
        ],
        activitySeries: DEMO_ACTIVITY_SERIES_EN,
        anomalyTypes: [
          { type: "Text similarity", count: 146 },
          { type: "Burst posting", count: 118 },
          { type: "Temporal clustering", count: 104 },
          { type: "Customer photo reuse", count: 91 },
          { type: "Weak product evidence", count: 84 },
          { type: "Bilingual slang signal", count: 73 },
          { type: "AI Text Check", count: 68 },
          { type: "Rating shift", count: 64 },
          { type: "Sentiment repetition", count: 58 },
          { type: "Photo vs review text", count: 57 },
          { type: "Photo OCR text", count: 52 },
          { type: "Author cluster", count: 46 },
          { type: "Timed photo cluster", count: 44 },
          { type: "Stock/marketing photos", count: 38 },
          { type: "Synthetic image hints", count: 21 },
        ],
        detectorCards: [
          {
            id: "text-similarity",
            name: "Text Similarity Spike",
            description: "Multiple review bodies share nearly identical wording and promotional phrasing.",
            severity: "high",
            score: 82,
            status: "critical",
          },
          {
            id: "weak-product-evidence",
            name: "Weak Product Evidence",
            description: "Separates real usage detail from generic claims about price, delivery, packaging, and quality without checkable experience.",
            severity: "medium",
            score: 66,
            status: "watch",
          },
          {
            id: "ai-text-review-risk",
            name: "AI Text Check",
            description: "Scores machine-polished review language, formulaic marketplace cliches, and weak grounding in real product use.",
            severity: "medium",
            score: 69,
            status: "watch",
          },
          {
            id: "burst-posting",
            name: "Burst Posting Pattern",
            description: "A dense block of reviews arrived in a compressed time window.",
            severity: "high",
            score: 76,
            status: "critical",
          },
          {
            id: "reviewer-trust",
            name: "Reviewer Trust Anomaly",
            description: "A subset of visible reviewers contributes a disproportionate number of reviews.",
            severity: "medium",
            score: 63,
            status: "watch",
          },
          {
            id: "rating-distribution",
            name: "Rating Distribution Shift",
            description: "Extremely positive ratings dominate the latest cluster of visible reviews.",
            severity: "medium",
            score: 58,
            status: "watch",
          },
          {
            id: "sentiment-repetition",
            name: "Sentiment Repetition",
            description: "The language tone repeats the same emotional framing across different authors.",
            severity: "medium",
            score: 61,
            status: "watch",
          },
          {
            id: "bilingual-slang",
            name: "Bilingual Slang Check",
            description: "Mixed RU/EN slang shows up in a hype-heavy pattern instead of grounded customer detail.",
            severity: "medium",
            score: 59,
            status: "watch",
          },
          {
            id: "customer-photo-reuse",
            name: "Customer Photo Reuse",
            description: "Two reviews reuse the same customer-photo asset with different CDN query parameters.",
            severity: "medium",
            score: 64,
            status: "watch",
          },
          {
            id: "timed-photo-cluster",
            name: "Timed Photo Cluster",
            description: "The same image appears across different authors in a short window, suggesting a coordinated campaign.",
            severity: "high",
            score: 72,
            status: "watch",
          },
          {
            id: "image-text-alignment",
            name: "Photo vs Review Text",
            description: "CLIP/ViT similarity flags photos that weakly match the review text and product category.",
            severity: "medium",
            score: 67,
            status: "watch",
          },
          {
            id: "stock-marketing-photo",
            name: "Stock/Marketing Photos",
            description: "One photo signal looks closer to a catalog or studio asset than a customer snapshot.",
            severity: "medium",
            score: 62,
            status: "watch",
          },
          {
            id: "ai-synthetic-image",
            name: "AI/Synthetic Image Hint",
            description: "Weak synthetic-cue hint; not used as standalone proof.",
            severity: "low",
            score: 41,
            status: "stable",
          },
          {
            id: "image-ocr-text",
            name: "Photo OCR Text",
            description: "The photo contains sale/watermark/marketplace text that does not look like a normal customer snapshot.",
            severity: "medium",
            score: 57,
            status: "watch",
          },
          {
            id: "temporal-clustering",
            name: "Temporal Clustering",
            description: "Review timestamps form short-lived spikes instead of organic long-tail activity.",
            severity: "high",
            score: 79,
            status: "critical",
          },
        ],
        explainability: [
          {
            label: "High textual similarity across reviews",
            weight: 0.25,
            narrative: "The model found repeated lexical structures and near-duplicate phrases across multiple authors.",
          },
          {
            label: "Burst of reviews in a short interval",
            weight: 0.2,
            narrative: "Posting activity is compressed into a narrow time band, which is unusual for organic feedback.",
          },
          {
            label: "Photo, OCR, and image reuse signals",
            weight: 0.18,
            narrative: "Reused photos, sale text inside images, and catalog-like assets increase the coordination signal.",
          },
          {
            label: "AI Text Check",
            weight: 0.14,
            narrative:
              "The detector accounts for machine-polished rhythm, long dash punctuation, delivery/packaging/price cliches, and weak checkable details.",
          },
          {
            label: "Low reviewer trust consistency",
            weight: 0.13,
            narrative: "Visible author behavior looks concentrated and less diverse than expected for a healthy product page.",
          },
          {
            label: "Rating distribution drift",
            weight: 0.1,
            narrative: "Recent ratings lean heavily toward the most extreme values, which amplifies manipulation risk.",
          },
        ],
        suspiciousReviews: [
          {
            id: "rvw-001",
            title: "Best purchase of the year, buy now",
            text: "Absolutely perfect, buy now, best purchase ever, every friend needs this immediately. Fast delivery, top product, 10 out of 10.",
            rating: 5,
            suspiciousness: 0.96,
            reason: "Promotional language, template text, and reused photo",
            author: "TopPick247",
            authorTrust: "low",
            date: "2026-04-13",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["best purchase ever", "must buy", "10/10", "top product", "buy now"],
            languageSignalScore: 0.91,
            languageAuthenticityScore: 0.1,
            languageDomain: "apparel",
            templateClustered: true,
            uncertaintyScore: 0.1,
            oodScore: 0.09,
            imageUrls: ["https://cdn.example.test/reviews/sandal-fit-42.jpg?w=640&q=80"],
            imageCount: 1,
            duplicateImageCount: 1,
            duplicateImageClusterSize: 4,
            duplicateImageScore: 0.87,
            duplicateImageFlag: true,
            imageTemporalClusterScore: 0.74,
            imageTemporalClusterFlag: true,
            imageTemporalClusterSize: 4,
            imageTemporalClusterAuthorCount: 4,
            imageTemporalClusterWindowHours: 36,
            imageTextAlignmentScore: 0.22,
            imageTextMismatchScore: 0.76,
            imageTextMismatchFlag: true,
            imageTextAlignmentLabel: "strong_mismatch",
            imageStockMarketingScore: 0.71,
            imageStockMarketingFlag: true,
            imageStockMarketingLabel: "stock_catalog",
            imageSyntheticScore: 0.58,
            imageSyntheticFlag: true,
            imageSyntheticLabel: "weak_synthetic_hint",
            imageOcrScore: 0.66,
            imageOcrFlag: true,
            imageOcrText: "SALE BEST PRODUCT Amazon official store",
            imageOcrLabels: ["sale_discount", "hype_claim", "foreign_marketplace_watermark"],
            aiTextScore: 0.78,
            aiTextFlag: true,
            aiTextLabel: "likely_ai_text",
            aiTextReasons: [
              "AI-text detector flagged polished/template-like review language; treat this as a moderation signal, not proof.",
              "The text uses long dash punctuation patterns that are common in polished generated reviews.",
            ],
          },
          {
            id: "rvw-002",
            title: "Five stars without a doubt",
            text: "Works amazing, flawless quality, must buy, 100 percent recommended to everyone. Very comfortable, great price, best choice.",
            rating: 5,
            suspiciousness: 0.91,
            reason: "Sentiment repetition and burst-posting cluster",
            author: "dailydeal_mira",
            authorTrust: "low",
            date: "2026-04-13",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["fr", "must buy", "10/10 recommend", "best choice"],
            languageSignalScore: 0.84,
            languageAuthenticityScore: 0.17,
            languageDomain: "apparel",
            templateClustered: true,
            uncertaintyScore: 0.2,
            oodScore: 0.14,
            imageUrls: ["https://cdn.example.test/reviews/sandal-fit-42.jpg?w=320&q=70"],
            imageCount: 1,
            duplicateImageCount: 1,
            duplicateImageClusterSize: 4,
            duplicateImageScore: 0.87,
            duplicateImageFlag: true,
            imageTemporalClusterScore: 0.74,
            imageTemporalClusterFlag: true,
            imageTemporalClusterSize: 4,
            imageTemporalClusterAuthorCount: 4,
            imageTemporalClusterWindowHours: 36,
            aiTextScore: 0.72,
            aiTextFlag: true,
            aiTextLabel: "ai_text_signal",
            aiTextReasons: [
              "AI-text detector flagged polished/template-like review language; treat this as a moderation signal, not proof.",
            ],
          },
          {
            id: "rvw-003",
            title: "Repeated positives without details",
            text: "Great sandals, great fit, great quality, great comfort, great material, great product overall.",
            rating: 5,
            suspiciousness: 0.83,
            reason: "Low lexical diversity",
            author: "comfortshopper",
            authorTrust: "neutral",
            date: "2026-04-12",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["great", "good quality", "comfortable"],
            languageSignalScore: 0.49,
            languageAuthenticityScore: 0.42,
            languageDomain: "apparel",
            templateClustered: false,
            uncertaintyScore: 0.61,
            oodScore: 0.27,
            aiTextScore: 0.58,
            aiTextFlag: false,
            aiTextLabel: "weak_ai_text_hint",
            aiTextReasons: [
              "The text is polished but weakly grounded in concrete ownership, delivery, sizing, or usage details.",
            ],
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-004",
            title: "Short but perfect",
            text: "Perfect. Loved it. Must buy.",
            rating: 5,
            suspiciousness: 0.77,
            reason: "Extreme rating with generic explanation",
            author: "A1TopChoice",
            authorTrust: "low",
            date: "2026-04-10",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["must buy", "perfect"],
            languageSignalScore: 0.58,
            languageAuthenticityScore: 0.24,
            languageDomain: "apparel",
            templateClustered: false,
            uncertaintyScore: 0.62,
            oodScore: 0.31,
            imageUrls: ["https://cdn.example.test/reviews/sandal-box-single.jpg"],
            imageCount: 1,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            imageTextAlignmentScore: 0.34,
            imageTextMismatchScore: 0.46,
            imageTextMismatchFlag: false,
          },
          {
            id: "rvw-005",
            title: "Negative spike after partner conflict",
            text: "Everything is terrible, the product broke immediately, the seller is bad, do not recommend. Support is silent, money wasted.",
            rating: 1,
            suspiciousness: 0.86,
            reason: "Sudden negative cluster and repeated complaint wording",
            author: "angry_case_77",
            authorTrust: "low",
            date: "2026-04-13",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["do not recommend", "money wasted", "bad seller", "same complaint"],
            languageSignalScore: 0.72,
            languageAuthenticityScore: 0.23,
            languageDomain: "apparel",
            templateClustered: true,
            uncertaintyScore: 0.34,
            oodScore: 0.18,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-006",
            title: "Photo looks like catalog material",
            text: "Beautiful sandals, the photo shows a perfect product, I am buying again, everyone should order from this store.",
            rating: 5,
            suspiciousness: 0.81,
            reason: "Stock-like photo and weak text alignment",
            author: "style_market_pro",
            authorTrust: "neutral",
            date: "2026-04-12",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["perfect product", "everyone should order", "catalog-like photo"],
            languageSignalScore: 0.55,
            languageAuthenticityScore: 0.31,
            languageDomain: "apparel",
            templateClustered: false,
            uncertaintyScore: 0.44,
            oodScore: 0.24,
            imageUrls: ["https://cdn.example.test/reviews/catalog-sandal-white-bg.jpg"],
            imageCount: 2,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0.18,
            duplicateImageFlag: false,
            imageTextAlignmentScore: 0.28,
            imageTextMismatchScore: 0.64,
            imageTextMismatchFlag: true,
            imageTextAlignmentLabel: "weak_alignment",
            imageStockMarketingScore: 0.83,
            imageStockMarketingFlag: true,
            imageStockMarketingLabel: "studio_catalog",
            imageSyntheticScore: 0.22,
            imageSyntheticFlag: false,
          },
          {
            id: "rvw-007",
            title: "Author pattern is too similar",
            text: "Bought these for my wife, the size fit, delivery was normal. The structure looks close to several neighboring reviews.",
            rating: 4,
            suspiciousness: 0.68,
            reason: "Repeated author structure and moderate uncertainty",
            author: "buyer_4421",
            authorTrust: "neutral",
            date: "2026-04-09",
            severity: "low",
            triageStatus: "needs_manual_review",
            languageProfile: "neutral",
            detectedTerms: ["same author pattern", "size fit"],
            languageSignalScore: 0.29,
            languageAuthenticityScore: 0.63,
            languageDomain: "apparel",
            templateClustered: false,
            uncertaintyScore: 0.57,
            oodScore: 0.19,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-008",
            title: "Normal review for comparison",
            text: "I wore the sandals for two weeks. The footbed is soft, but the strap rubbed at first. After adjusting it, they became comfortable.",
            rating: 4,
            suspiciousness: 0.24,
            reason: "Contains concrete usage details",
            author: "realwalk_samara",
            authorTrust: "trusted",
            date: "2026-04-07",
            severity: "low",
            triageStatus: "confident_clean",
            languageProfile: "organic",
            detectedTerms: ["two weeks", "strap rubbed", "after adjusting"],
            languageSignalScore: 0.12,
            languageAuthenticityScore: 0.82,
            languageDomain: "apparel",
            templateClustered: false,
            uncertaintyScore: 0.16,
            oodScore: 0.07,
            imageUrls: ["https://cdn.example.test/reviews/real-wear-detail.jpg"],
            imageCount: 1,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            imageTextAlignmentScore: 0.78,
            imageTextMismatchScore: 0.08,
            imageTextMismatchFlag: false,
          },
          {
            id: "rvw-009",
            title: "One author praises many products",
            text: "This is already the fifth product I ordered from this seller, everything is always perfect, lightning delivery, best quality.",
            rating: 5,
            suspiciousness: 0.79,
            reason: "Unnatural author activity across several products",
            author: "multi_item_boost",
            authorTrust: "low",
            date: "2026-04-12",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["fifth product", "always perfect", "best quality", "multi-item pattern"],
            languageSignalScore: 0.52,
            languageAuthenticityScore: 0.35,
            languageDomain: "apparel",
            templateClustered: true,
            uncertaintyScore: 0.47,
            oodScore: 0.29,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-010",
            title: "Review with OCR watermark",
            text: "The photo fully shows the quality, best store, super discount, buy while the sizes are still available.",
            rating: 5,
            suspiciousness: 0.84,
            reason: "OCR text on the image and marketing-style wording",
            author: "sale_photo_user",
            authorTrust: "low",
            date: "2026-04-13",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["super discount", "best store", "OCR watermark", "sale banner"],
            languageSignalScore: 0.73,
            languageAuthenticityScore: 0.22,
            languageDomain: "apparel",
            templateClustered: true,
            uncertaintyScore: 0.31,
            oodScore: 0.21,
            imageUrls: ["https://cdn.example.test/reviews/sale-watermark-sandal.jpg"],
            imageCount: 1,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0.14,
            duplicateImageFlag: false,
            imageTextAlignmentScore: 0.32,
            imageTextMismatchScore: 0.59,
            imageTextMismatchFlag: true,
            imageTextAlignmentLabel: "weak_alignment",
            imageStockMarketingScore: 0.76,
            imageStockMarketingFlag: true,
            imageStockMarketingLabel: "marketing_banner",
            imageSyntheticScore: 0.31,
            imageSyntheticFlag: false,
            imageOcrScore: 0.88,
            imageOcrFlag: true,
            imageOcrText: "SUPER SALE -50% LIMITED OFFER",
            imageOcrLabels: ["discount_banner", "limited_offer", "watermark"],
          },
          {
            id: "rvw-011",
            title: "Overly neutral template",
            text: "The product matches the description, delivery was normal, seller communication was normal, overall everything is normal.",
            rating: 4,
            suspiciousness: 0.55,
            reason: "Repeated neutral template with little usage detail",
            author: "neutral_case_18",
            authorTrust: "neutral",
            date: "2026-04-08",
            severity: "low",
            triageStatus: "needs_manual_review",
            languageProfile: "neutral",
            detectedTerms: ["normal", "matches the description", "overall everything is normal"],
            languageSignalScore: 0.25,
            languageAuthenticityScore: 0.49,
            languageDomain: "apparel",
            templateClustered: true,
            uncertaintyScore: 0.52,
            oodScore: 0.16,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-012",
            title: "Detailed post-use review",
            text: "After a month of wear the sole has not collapsed, but the right strap has a scuff. Size 42 fit my 26.5 cm foot.",
            rating: 4,
            suspiciousness: 0.18,
            reason: "Organic review with checkable usage details",
            author: "verified_step_42",
            authorTrust: "trusted",
            date: "2026-04-05",
            severity: "low",
            triageStatus: "confident_clean",
            languageProfile: "organic",
            detectedTerms: ["month of wear", "right strap", "26.5 cm"],
            languageSignalScore: 0.08,
            languageAuthenticityScore: 0.88,
            languageDomain: "apparel",
            templateClustered: false,
            uncertaintyScore: 0.12,
            oodScore: 0.05,
            imageUrls: ["https://cdn.example.test/reviews/wear-after-month.jpg"],
            imageCount: 1,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            imageTextAlignmentScore: 0.84,
            imageTextMismatchScore: 0.06,
            imageTextMismatchFlag: false,
          },
          {
            id: "rvw-013",
            title: "Short clean marketplace review",
            text: "Size fit, the strap does not rub. Packaging was intact.",
            rating: 5,
            suspiciousness: 0.05,
            reason: "Short marketplace review with concrete details and no promo template",
            author: "size_fit_05",
            authorTrust: "trusted",
            date: "2026-04-04",
            severity: "low",
            triageStatus: "confident_clean",
            languageProfile: "organic",
            detectedTerms: ["size fit", "strap", "packaging intact"],
            languageSignalScore: 0.07,
            languageAuthenticityScore: 0.76,
            languageDomain: "apparel",
            templateClustered: false,
            uncertaintyScore: 0.14,
            oodScore: 0.08,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            aiTextScore: 0.11,
            aiTextFlag: false,
            aiTextLabel: "marketplace_clean",
            aiTextReasons: [
              "The short text contains checkable purchase details and does not look like a promotional template.",
            ],
          },
        ],
        keyInsights: [
          "A quiet period is followed by an abrupt review spike with a high suspicious-review share.",
          "Several reviews repeat promotional wording and mix Russian/English hype language without concrete usage detail.",
          "AI Text Check exposes a separate score, including machine-polished phrasing, long dash punctuation, repeated cliches, and weak purchase details.",
          "Photo signals include reused images, OCR sale text, and catalog-style assets.",
          "The table demonstrates multiple triage states: confident suspicious, manual review, and clean examples including a short low-risk marketplace review.",
        ],
      };
}

function getSiteDataPreviewResult(locale: Locale): DashboardResult {
  const base = getHeroPreviewResult(locale);

  return {
    ...base,
    sourceMode: "records",
    overview: locale === "ru"
      ? {
          productName: "Platform Integrity Dataset",
          sourceLabel: "site-data",
          statusLabel: "Критический кластер риска",
          riskScore: 87,
          manipulationProbability: 82,
          confidence: 95,
          reviewCount: 840,
          suspiciousCount: 136,
          manualReviewCount: 58,
          verdict:
            "Структурированные записи показывают подозрительные кластеры пользователей, повторяющиеся IP, резкие рейтинговые сдвиги и группы отзывов, требующие ручной проверки.",
        }
      : {
          productName: "Platform Integrity Dataset",
          sourceLabel: "site-data",
          statusLabel: "Critical fraud cluster",
          riskScore: 87,
          manipulationProbability: 82,
          confidence: 95,
          reviewCount: 840,
          suspiciousCount: 136,
          manualReviewCount: 58,
          verdict:
            "The structured site records reveal suspicious user clusters, repeated IP usage, sharp rating shifts, and review groups that warrant manual moderation.",
        },
    trustBreakdown: locale === "ru"
      ? [
          { name: "Надежные", value: 646, fill: "#0f766e" },
          { name: "Подозрительные", value: 136, fill: "#c35e43" },
          { name: "Неопределенные", value: 58, fill: "#c4872f" },
        ]
      : [
          { name: "Trustworthy", value: 646, fill: "#0f766e" },
          { name: "Suspicious", value: 136, fill: "#c35e43" },
          { name: "Uncertain", value: 58, fill: "#c4872f" },
        ],
        anomalyTypes: locale === "ru"
      ? [
          { type: "Кластер аккаунтов", count: 128 },
          { type: "Проверка IP-адресов", count: 96 },
          { type: "Всплеск публикаций", count: 74 },
          { type: "Сдвиг рейтингов", count: 61 },
          { type: "Повтор текста", count: 54 },
          { type: "IP-всплеск за час", count: 42 },
          { type: "Проверка на AI", count: 37 },
          { type: "Фото/OCR-сигналы", count: 24 },
          { type: "Низкая история автора", count: 22 },
        ]
      : [
          { type: "Account cluster", count: 128 },
          { type: "IP Address Check", count: 96 },
          { type: "Burst posting", count: 74 },
          { type: "Rating shift", count: 61 },
          { type: "Repeated text", count: 54 },
          { type: "Hourly IP burst", count: 42 },
          { type: "AI Text Check", count: 37 },
          { type: "Photo/OCR signals", count: 24 },
          { type: "Thin author history", count: 22 },
        ],
    detectorCards: locale === "ru"
      ? [
          {
            id: "account-cluster",
            name: "Кластер аккаунтов",
            description: "Группа пользователей создает отзывы в похожем временном окне и с близкими поведенческими признаками.",
            severity: "high",
            score: 88,
            status: "critical",
          },
          {
            id: "ip-device-repeat",
            name: "Проверка IP-адресов",
            description: "Проверяет общий IP у разных аккаунтов, число пользователей на одном IP и всплески оценок с IP за короткое окно.",
            severity: "high",
            score: 84,
            status: "critical",
          },
          {
            id: "burst-posting",
            name: "Всплеск публикаций",
            description: "Отзывы пришли плотной пачкой после долгого спокойного периода.",
            severity: "high",
            score: 78,
            status: "critical",
          },
          {
            id: "rating-distribution",
            name: "Сдвиг рейтингов",
            description: "В одном сегменте резко выросла доля крайних оценок.",
            severity: "medium",
            score: 68,
            status: "watch",
          },
          {
            id: "text-similarity",
            name: "Повтор текста",
            description: "Отзывы используют похожие формулировки, порядок аргументов и одинаковые коммерческие связки.",
            severity: "medium",
            score: 65,
            status: "watch",
          },
          {
            id: "ai-text-review-risk",
            name: "Проверка на AI",
            description: "Отдельно подсвечивает машинно выверенную подачу, длинное тире и шаблонные фразы без реальной конкретики.",
            severity: "medium",
            score: 61,
            status: "watch",
          },
          {
            id: "media-records",
            name: "Фото/OCR-сигналы",
            description: "Медиа-поля показывают повторы изображений, рекламный текст на фото и слабую связь с отзывом.",
            severity: "medium",
            score: 56,
            status: "watch",
          },
          {
            id: "thin-author-history",
            name: "Низкая история автора",
            description: "Часть аккаунтов почти не имеет нормальной истории до подозрительного всплеска.",
            severity: "low",
            score: 47,
            status: "stable",
          },
        ]
      : [
          {
            id: "account-cluster",
            name: "Account Cluster",
            description: "A user group posts in a similar time window and shares close behavioral attributes.",
            severity: "high",
            score: 88,
            status: "critical",
          },
          {
            id: "ip-device-repeat",
            name: "IP Address Check",
            description: "Checks shared IPs across accounts, user count per IP, and rating bursts from the same IP in a short window.",
            severity: "high",
            score: 84,
            status: "critical",
          },
          {
            id: "burst-posting",
            name: "Burst Posting",
            description: "Reviews arrived as a dense batch after a long quiet period.",
            severity: "high",
            score: 78,
            status: "critical",
          },
          {
            id: "rating-distribution",
            name: "Rating Shift",
            description: "One segment shows a sudden increase in extreme ratings.",
            severity: "medium",
            score: 68,
            status: "watch",
          },
          {
            id: "text-similarity",
            name: "Repeated Text",
            description: "Reviews reuse similar wording, argument order, and commercial connectors.",
            severity: "medium",
            score: 65,
            status: "watch",
          },
          {
            id: "ai-text-review-risk",
            name: "AI Text Check",
            description: "Separately highlights machine-polished wording, long dash punctuation, and generic phrases without real detail.",
            severity: "medium",
            score: 61,
            status: "watch",
          },
          {
            id: "media-records",
            name: "Photo/OCR Signals",
            description: "Media fields show reused images, promotional text in photos, and weak review-image alignment.",
            severity: "medium",
            score: 56,
            status: "watch",
          },
          {
            id: "thin-author-history",
            name: "Thin Author History",
            description: "Some accounts have almost no normal history before the suspicious spike.",
            severity: "low",
            score: 47,
            status: "stable",
          },
        ],
    explainability: locale === "ru"
      ? [
          {
            label: "IP-адреса и связанные аккаунты",
            weight: 0.26,
            narrative: "Самый сильный вклад дают общий IP у нескольких аккаунтов, всплески оценок с одного IP за час и связанные авторские паттерны.",
          },
          {
            label: "Плотный временной всплеск",
            weight: 0.2,
            narrative: "Много отзывов пришло в коротком окне после периода низкой активности.",
          },
          {
            label: "Сдвиг рейтингов и полярности",
            weight: 0.18,
            narrative: "Сегмент резко сместился к крайним оценкам, поэтому риск не сводится только к тексту.",
          },
          {
            label: "Повтор текста и Проверка на AI",
            weight: 0.16,
            narrative: "Шаблонные формулировки, длинное тире и одинаковая структура усиливают сигнал синтетической подачи.",
          },
          {
            label: "Медиа/OCR-сигналы",
            weight: 0.11,
            narrative: "Повторы изображений и текст распродажи на фото добавляют контекст к пользовательским кластерам.",
          },
          {
            label: "Низкая история автора",
            weight: 0.09,
            narrative: "Часть авторов выглядит слишком новой или узкой по поведению для устойчивой органической выборки.",
          },
        ]
      : [
          {
            label: "IP addresses and linked accounts",
            weight: 0.26,
            narrative: "The strongest contribution comes from shared IPs across accounts, hourly rating bursts from one IP, and linked author patterns.",
          },
          {
            label: "Dense temporal spike",
            weight: 0.2,
            narrative: "Many reviews arrived in a short window after a low-activity period.",
          },
          {
            label: "Rating and polarity shift",
            weight: 0.18,
            narrative: "The segment sharply shifted toward extreme ratings, so the risk is not purely textual.",
          },
          {
            label: "Repeated text and AI Text Check",
            weight: 0.16,
            narrative: "Template phrasing, long dash punctuation, and repeated structure increase the synthetic-language signal.",
          },
          {
            label: "Media/OCR signals",
            weight: 0.11,
            narrative: "Reused images and sale text inside photos add context to the user clusters.",
          },
          {
            label: "Thin author history",
            weight: 0.09,
            narrative: "Some authors look too new or narrow in behavior for a healthy organic sample.",
          },
        ],
    suspiciousReviews: locale === "ru"
      ? [
          {
            id: "rec-001",
            title: "Позитивный кластер с одним отпечатком",
            text: "Цена адекватная — не жалко платить за результат. Доставка/поддержка/упаковка — приятно удивили.",
            rating: 5,
            suspiciousness: 0.94,
            reason: "Один IP у группы аккаунтов, повтор технического отпечатка и AI-текст",
            author: "u_cluster_17",
            authorTrust: "low",
            date: "2026-04-12",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["один IP у нескольких аккаунтов", "IP-всплеск за час", "цена адекватная", "приятно удивили"],
            languageSignalScore: 0.86,
            languageAuthenticityScore: 0.14,
            languageDomain: "site-records",
            templateClustered: true,
            uncertaintyScore: 0.12,
            oodScore: 0.08,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            aiTextScore: 0.82,
            aiTextFlag: true,
            aiTextLabel: "likely_ai_text",
            aiTextReasons: ["Шаблонная подача, длинное тире и универсальные сервисные клише без деталей товара."],
          },
          {
            id: "rec-002",
            title: "Резкая негативная атака",
            text: "Товар ужасный, продавец обманывает, поддержка молчит, деньги потеряны. Не рекомендую никому.",
            rating: 1,
            suspiciousness: 0.89,
            reason: "Короткий негативный всплеск с повтором жалоб",
            author: "refund_wave_04",
            authorTrust: "low",
            date: "2026-04-11",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["не рекомендую", "деньги потеряны", "поддержка молчит"],
            languageSignalScore: 0.72,
            languageAuthenticityScore: 0.2,
            languageDomain: "site-records",
            templateClustered: true,
            uncertaintyScore: 0.18,
            oodScore: 0.11,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rec-003",
            title: "Одинаковое фото у разных авторов",
            text: "Все отлично, качество топ, фото подтверждает, берите смело.",
            rating: 5,
            suspiciousness: 0.78,
            reason: "Повтор изображения и слабая конкретика",
            author: "photo_chain_22",
            authorTrust: "neutral",
            date: "2026-04-10",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["качество топ", "берите смело", "повтор фото"],
            languageSignalScore: 0.58,
            languageAuthenticityScore: 0.32,
            languageDomain: "site-records",
            templateClustered: true,
            uncertaintyScore: 0.42,
            oodScore: 0.18,
            imageUrls: ["https://cdn.example.test/reviews/shared-record-photo.jpg"],
            imageCount: 1,
            duplicateImageCount: 1,
            duplicateImageClusterSize: 6,
            duplicateImageScore: 0.84,
            duplicateImageFlag: true,
            imageOcrScore: 0.71,
            imageOcrFlag: true,
            imageOcrText: "SALE LIMITED",
            imageOcrLabels: ["sale_discount", "watermark"],
          },
          {
            id: "rec-004",
            title: "Пограничный отзыв для модератора",
            text: "Заказ пришел вовремя, но коробка была помята. Сам товар работает, пока наблюдаю.",
            rating: 4,
            suspiciousness: 0.46,
            reason: "Нейтральный текст, но автор попал в слабый кластер",
            author: "mixed_case_08",
            authorTrust: "neutral",
            date: "2026-04-09",
            severity: "low",
            triageStatus: "needs_manual_review",
            languageProfile: "neutral",
            detectedTerms: ["коробка помята", "пока наблюдаю"],
            languageSignalScore: 0.22,
            languageAuthenticityScore: 0.61,
            languageDomain: "site-records",
            templateClustered: false,
            uncertaintyScore: 0.54,
            oodScore: 0.2,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rec-005",
            title: "Чистый ориентир",
            text: "Пользуюсь три недели. Один раз зависло приложение, после обновления проблема ушла.",
            rating: 4,
            suspiciousness: 0.12,
            reason: "Проверяемая история использования и нормальная история автора",
            author: "verified_user_31",
            authorTrust: "trusted",
            date: "2026-04-07",
            severity: "low",
            triageStatus: "confident_clean",
            languageProfile: "organic",
            detectedTerms: ["три недели", "после обновления", "проблема ушла"],
            languageSignalScore: 0.09,
            languageAuthenticityScore: 0.83,
            languageDomain: "site-records",
            templateClustered: false,
            uncertaintyScore: 0.15,
            oodScore: 0.06,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            aiTextScore: 0.08,
            aiTextFlag: false,
            aiTextLabel: "organic_text",
          },
        ]
      : [
          {
            id: "rec-001",
            title: "Positive cluster with one fingerprint",
            text: "The price feels fair — paying for the result does not hurt. Delivery/support/packaging were a pleasant surprise.",
            rating: 5,
            suspiciousness: 0.94,
            reason: "One IP is shared by an account group, with repeated technical fingerprint and AI-text signal",
            author: "u_cluster_17",
            authorTrust: "low",
            date: "2026-04-12",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["one IP across accounts", "hourly IP burst", "fair price", "pleasant surprise"],
            languageSignalScore: 0.86,
            languageAuthenticityScore: 0.14,
            languageDomain: "site-records",
            templateClustered: true,
            uncertaintyScore: 0.12,
            oodScore: 0.08,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            aiTextScore: 0.82,
            aiTextFlag: true,
            aiTextLabel: "likely_ai_text",
            aiTextReasons: ["Template wording, long dash punctuation, and generic service cliches without product details."],
          },
          {
            id: "rec-002",
            title: "Sharp negative attack",
            text: "The product is terrible, the seller lies, support is silent, money wasted. I do not recommend it to anyone.",
            rating: 1,
            suspiciousness: 0.89,
            reason: "Short negative spike with repeated complaint wording",
            author: "refund_wave_04",
            authorTrust: "low",
            date: "2026-04-11",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["do not recommend", "money wasted", "support is silent"],
            languageSignalScore: 0.72,
            languageAuthenticityScore: 0.2,
            languageDomain: "site-records",
            templateClustered: true,
            uncertaintyScore: 0.18,
            oodScore: 0.11,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rec-003",
            title: "Same photo across authors",
            text: "Everything is great, top quality, the photo proves it, buy with confidence.",
            rating: 5,
            suspiciousness: 0.78,
            reason: "Reused image and weak concrete detail",
            author: "photo_chain_22",
            authorTrust: "neutral",
            date: "2026-04-10",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["top quality", "buy with confidence", "reused photo"],
            languageSignalScore: 0.58,
            languageAuthenticityScore: 0.32,
            languageDomain: "site-records",
            templateClustered: true,
            uncertaintyScore: 0.42,
            oodScore: 0.18,
            imageUrls: ["https://cdn.example.test/reviews/shared-record-photo.jpg"],
            imageCount: 1,
            duplicateImageCount: 1,
            duplicateImageClusterSize: 6,
            duplicateImageScore: 0.84,
            duplicateImageFlag: true,
            imageOcrScore: 0.71,
            imageOcrFlag: true,
            imageOcrText: "SALE LIMITED",
            imageOcrLabels: ["sale_discount", "watermark"],
          },
          {
            id: "rec-004",
            title: "Borderline moderator case",
            text: "The order arrived on time, but the box was dented. The product itself works, I am still watching it.",
            rating: 4,
            suspiciousness: 0.46,
            reason: "Neutral text, but the author belongs to a weak cluster",
            author: "mixed_case_08",
            authorTrust: "neutral",
            date: "2026-04-09",
            severity: "low",
            triageStatus: "needs_manual_review",
            languageProfile: "neutral",
            detectedTerms: ["dented box", "still watching"],
            languageSignalScore: 0.22,
            languageAuthenticityScore: 0.61,
            languageDomain: "site-records",
            templateClustered: false,
            uncertaintyScore: 0.54,
            oodScore: 0.2,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rec-005",
            title: "Clean baseline",
            text: "I have used it for three weeks. The app froze once, and the issue disappeared after the update.",
            rating: 4,
            suspiciousness: 0.12,
            reason: "Checkable usage history and normal author history",
            author: "verified_user_31",
            authorTrust: "trusted",
            date: "2026-04-07",
            severity: "low",
            triageStatus: "confident_clean",
            languageProfile: "organic",
            detectedTerms: ["three weeks", "after the update", "issue disappeared"],
            languageSignalScore: 0.09,
            languageAuthenticityScore: 0.83,
            languageDomain: "site-records",
            templateClustered: false,
            uncertaintyScore: 0.15,
            oodScore: 0.06,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
            aiTextScore: 0.08,
            aiTextFlag: false,
            aiTextLabel: "organic_text",
          },
        ],
    keyInsights: locale === "ru"
      ? [
          "В structured records демо отдельно показана проверка IP-адресов: общий IP у аккаунтов, всплески за час и слабая история авторов.",
          "Подозрительность не завязана только на тексте: рейтинг, время, технические отпечатки и медиа-сигналы показаны отдельными группами.",
          "Проверка на AI оставлена как вспомогательный сигнал, а не как единственное доказательство.",
          "В таблице есть уверенно подозрительные записи, пограничная ручная проверка и чистый ориентир.",
        ]
      : [
          "The structured-records demo now separately shows IP address checks: shared account IPs, hourly bursts, and thin author history.",
          "Risk is not text-only: rating, timing, technical fingerprints, and media signals are represented as separate groups.",
          "AI Text Check remains a supporting signal, not standalone proof.",
          "The table includes confident suspicious records, a borderline manual case, and a clean baseline.",
        ],
  };
}

export function getDemoResult(mode: SourceMode, locale: Locale): DashboardResult {
  return mode === "records" ? getSiteDataPreviewResult(locale) : getHeroPreviewResult(locale);
}
