import type {
  AnalysisFormValues,
  DashboardResult,
  PipelineStage,
  SourceMode,
} from "../types/analysis";
import type { Locale } from "../i18n";

export const defaultFormValues: AnalysisFormValues = {
  sourceMode: "url",
  url: "",
  html: "",
  recordsJson: "",
  recordsFileName: "",
  sourceUrl: "",
  analysisDepth: "standard",
  waitMs: "",
};

export const PIPELINE_STAGE_COUNT = 5;

export function getBasePipelineStages(locale: Locale): PipelineStage[] {
  return locale === "ru"
    ? [
        {
          key: "collect",
          label: "Сбор страницы",
          description: "Получаем страницу товара или загружаем переданный источник.",
          state: "pending",
        },
        {
          key: "extract",
          label: "Извлечение отзывов",
          description: "Парсим HTML и нормализуем блоки с отзывами.",
          state: "pending",
        },
        {
          key: "features",
          label: "Построение признаков",
          description: "Генерируем NLP, временные и поведенческие антифрод-сигналы.",
          state: "pending",
        },
        {
          key: "analyze",
          label: "Запуск модели",
          description: "Применяем ML и поиск аномалий ко всему набору отзывов.",
          state: "pending",
        },
        {
          key: "profile",
          label: "Риск-профиль",
          description: "Собираем финальное объяснение и moderation-дашборд.",
          state: "pending",
        },
      ]
    : [
        {
          key: "collect",
          label: "Collect page",
          description: "Fetching the product page or loading the provided source.",
          state: "pending",
        },
        {
          key: "extract",
          label: "Extract reviews",
          description: "Parsing the HTML and normalizing review blocks.",
          state: "pending",
        },
        {
          key: "features",
          label: "Build features",
          description: "Generating NLP, temporal, and behavioral fraud signals.",
          state: "pending",
        },
        {
          key: "analyze",
          label: "Run model",
          description: "Applying ML and anomaly detection across the review set.",
          state: "pending",
        },
        {
          key: "profile",
          label: "Risk profile",
          description: "Building the final explanation and moderation dashboard.",
          state: "pending",
        },
      ];
}

function getHeroPreviewResult(locale: Locale): DashboardResult {
  return locale === "ru"
    ? {
        sourceMode: "url",
        overview: {
          productName: "TEMOFON Cork Footbed Sandals",
          sourceLabel: "amazon.com",
          statusLabel: "Повышенный риск",
          riskScore: 74,
          manipulationProbability: 69,
          confidence: 92,
          reviewCount: 148,
          suspiciousCount: 34,
          manualReviewCount: 25,
          verdict:
            "Текущая выборка отзывов содержит повторяющиеся sentiment-паттерны, кластерную публикацию и заметные сдвиги в рейтинговом поведении.",
        },
        trustBreakdown: [
          { name: "Надежные", value: 89, fill: "#0f766e" },
          { name: "Подозрительные", value: 34, fill: "#c35e43" },
          { name: "Неопределенные", value: 25, fill: "#c4872f" },
        ],
        activitySeries: [
          { label: "Пн", reviews: 11, suspicious: 1 },
          { label: "Вт", reviews: 14, suspicious: 2 },
          { label: "Ср", reviews: 18, suspicious: 3 },
          { label: "Чт", reviews: 22, suspicious: 5 },
          { label: "Пт", reviews: 29, suspicious: 8 },
          { label: "Сб", reviews: 31, suspicious: 9 },
          { label: "Вс", reviews: 23, suspicious: 6 },
        ],
        anomalyTypes: [
          { type: "Текстовая схожесть", count: 14 },
          { type: "Всплеск публикаций", count: 11 },
          { type: "Временной кластер", count: 9 },
          { type: "Bilingual slang signal", count: 8 },
          { type: "Сдвиг рейтингов", count: 7 },
          { type: "Повтор sentiment-фрейминга", count: 6 },
        ],
        detectorCards: [
          {
            id: "text-similarity",
            name: "Пик текстовой схожести",
            description: "Несколько отзывов используют почти одинаковые формулировки и промо-тон.",
            severity: "high",
            score: 82,
            status: "critical",
          },
          {
            id: "burst-posting",
            name: "Паттерн всплеска публикаций",
            description: "Плотный блок отзывов появился в очень коротком временном окне.",
            severity: "high",
            score: 76,
            status: "critical",
          },
          {
            id: "reviewer-trust",
            name: "Аномалия доверия к авторам",
            description: "Часть видимых авторов дает непропорционально много отзывов.",
            severity: "medium",
            score: 63,
            status: "watch",
          },
          {
            id: "rating-distribution",
            name: "Сдвиг распределения рейтингов",
            description: "В последнем кластере видимых отзывов доминируют экстремально позитивные оценки.",
            severity: "medium",
            score: 58,
            status: "watch",
          },
          {
            id: "sentiment-repetition",
            name: "Повтор sentiment-паттернов",
            description: "Тональность повторяет один и тот же эмоциональный шаблон у разных авторов.",
            severity: "medium",
            score: 61,
            status: "watch",
          },
          {
            id: "bilingual-slang",
            name: "Проверка bilingual slang",
            description: "Смешанный RU/EN slang встречается скорее как hype-паттерн, а не как grounded customer detail.",
            severity: "medium",
            score: 59,
            status: "watch",
          },
          {
            id: "customer-photo-reuse",
            name: "Дубликаты фото покупателей",
            description: "Два отзыва переиспользуют один и тот же customer-photo asset с разными CDN-параметрами.",
            severity: "medium",
            score: 64,
            status: "watch",
          },
          {
            id: "timed-photo-cluster",
            name: "Временной кластер фото",
            description: "Одно и то же фото появляется у разных авторов в коротком окне, что похоже на coordinated campaign.",
            severity: "high",
            score: 72,
            status: "watch",
          },
          {
            id: "image-text-alignment",
            name: "Фото vs текст отзыва",
            description: "CLIP/ViT similarity помечает фото, которые визуально слабее совпадают с текстом отзыва и категорией товара.",
            severity: "medium",
            score: 67,
            status: "watch",
          },
          {
            id: "stock-marketing-photo",
            name: "Стоковые/маркетинговые фото",
            description: "Один из photo-сигналов похож на каталожный или студийный asset вместо customer snapshot.",
            severity: "medium",
            score: 62,
            status: "watch",
          },
          {
            id: "ai-synthetic-image",
            name: "AI/synthetic image hint",
            description: "Слабая подсказка по synthetic cues; не используется как самостоятельное доказательство.",
            severity: "low",
            score: 41,
            status: "stable",
          },
          {
            id: "image-ocr-text",
            name: "OCR текста на фото",
            description: "На фото найден sale/watermark/marketplace текст, который не похож на обычный customer snapshot.",
            severity: "medium",
            score: 57,
            status: "watch",
          },
          {
            id: "temporal-clustering",
            name: "Временная кластеризация",
            description: "Метки времени формируют короткие пики вместо органичного long-tail-потока.",
            severity: "high",
            score: 79,
            status: "critical",
          },
        ],
        explainability: [
          {
            label: "Высокая текстовая схожесть между отзывами",
            weight: 0.31,
            narrative: "Модель нашла повторяющиеся лексические структуры и почти дублирующиеся фразы у нескольких авторов.",
          },
          {
            label: "Всплеск отзывов в коротком интервале",
            weight: 0.24,
            narrative: "Активность публикаций сжата в узкий временной диапазон, что нетипично для органической обратной связи.",
          },
          {
            label: "Низкая устойчивость reviewer trust",
            weight: 0.18,
            narrative: "Поведение видимых авторов выглядит более концентрированным и менее разнообразным, чем ожидается для здоровой страницы товара.",
          },
          {
            label: "Дрейф распределения рейтингов",
            weight: 0.16,
            narrative: "Недавние оценки слишком сильно тяготеют к экстремальным значениям, что усиливает риск манипуляции.",
          },
          {
            label: "Повтор эмоционального фрейминга",
            weight: 0.11,
            narrative: "Несколько отзывов переиспользуют одинаковую полярность и sales-style язык вместо конкретных деталей о товаре.",
          },
        ],
        suspiciousReviews: [
          {
            id: "rvw-001",
            title: "Лучшая покупка года",
            text: "Абсолютно идеально, берите сейчас, лучшая покупка, всем друзьям срочно нужно это купить.",
            rating: 5,
            suspiciousness: 0.94,
            reason: "Промо-язык + высокая текстовая схожесть",
            author: "TopPick247",
            authorTrust: "low",
            date: "2026-04-11",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["best purchase ever", "must buy", "fire"],
            languageSignalScore: 0.88,
            languageAuthenticityScore: 0.12,
            languageDomain: "одежда",
            templateClustered: true,
            uncertaintyScore: 0.12,
            oodScore: 0.08,
            imageUrls: ["https://cdn.example.test/reviews/sandal-fit-42.jpg?w=640&q=80"],
            imageCount: 1,
            duplicateImageCount: 1,
            duplicateImageClusterSize: 2,
            duplicateImageScore: 0.79,
            duplicateImageFlag: true,
            imageTemporalClusterScore: 0.66,
            imageTemporalClusterFlag: true,
            imageTemporalClusterSize: 2,
            imageTemporalClusterAuthorCount: 2,
            imageTemporalClusterWindowHours: 48,
            imageTextAlignmentScore: 0.22,
            imageTextMismatchScore: 0.71,
            imageTextMismatchFlag: true,
            imageTextAlignmentLabel: "strong_mismatch",
            imageStockMarketingScore: 0.68,
            imageStockMarketingFlag: true,
            imageStockMarketingLabel: "stock_catalog",
            imageSyntheticScore: 0.69,
            imageSyntheticFlag: true,
            imageSyntheticLabel: "weak_synthetic_hint",
            imageOcrScore: 0.62,
            imageOcrFlag: true,
            imageOcrText: "SALE BEST PRODUCT Amazon official store",
            imageOcrLabels: ["sale_discount", "hype_claim", "foreign_marketplace_watermark"],
          },
          {
            id: "rvw-002",
            title: "Пять звезд без сомнений",
            text: "Работает шикарно, качество безупречное, must buy, 100 процентов рекомендую всем.",
            rating: 5,
            suspiciousness: 0.88,
            reason: "Повтор sentiment-а + burst-паттерн",
            author: "dailydeal_mira",
            authorTrust: "low",
            date: "2026-04-11",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["fr", "must buy", "10/10 recommend"],
            languageSignalScore: 0.81,
            languageAuthenticityScore: 0.18,
            languageDomain: "одежда",
            templateClustered: true,
            uncertaintyScore: 0.18,
            oodScore: 0.12,
            imageUrls: ["https://cdn.example.test/reviews/sandal-fit-42.jpg?w=320&q=70"],
            imageCount: 1,
            duplicateImageCount: 1,
            duplicateImageClusterSize: 2,
            duplicateImageScore: 0.79,
            duplicateImageFlag: true,
            imageTemporalClusterScore: 0.66,
            imageTemporalClusterFlag: true,
            imageTemporalClusterSize: 2,
            imageTemporalClusterAuthorCount: 2,
            imageTemporalClusterWindowHours: 48,
          },
          {
            id: "rvw-003",
            title: "Правда хороший товар",
            text: "Хорошие сандалии, хорошая посадка, хорошее качество, хороший комфорт, в целом хороший товар.",
            rating: 5,
            suspiciousness: 0.82,
            reason: "Низкое лексическое разнообразие",
            author: "comfortshopper",
            authorTrust: "neutral",
            date: "2026-04-10",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["great", "clean"],
            languageSignalScore: 0.43,
            languageAuthenticityScore: 0.54,
            languageDomain: "одежда",
            templateClustered: false,
            uncertaintyScore: 0.58,
            oodScore: 0.22,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-004",
            title: "Коротко, но идеально",
            text: "Идеально. Понравилось. Must buy.",
            rating: 5,
            suspiciousness: 0.77,
            reason: "Экстремальная оценка при слишком общей аргументации",
            author: "A1TopChoice",
            authorTrust: "low",
            date: "2026-04-10",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["must buy", "perfect"],
            languageSignalScore: 0.58,
            languageAuthenticityScore: 0.24,
            languageDomain: "одежда",
            templateClustered: false,
            uncertaintyScore: 0.62,
            oodScore: 0.31,
            imageUrls: ["https://cdn.example.test/reviews/sandal-box-single.jpg"],
            imageCount: 1,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
        ],
        keyInsights: [
          "Активность отзывов показывает резкий поздний всплеск.",
          "Концентрированная группа отзывов смешивает русский и английский slang в промо-heavy тоне.",
          "Обнаружен повторяющийся эмоциональный шаблон у нескольких авторов.",
          "Концентрация авторов выше, чем ожидается для этой выборки.",
        ],
      }
    : {
        sourceMode: "url",
        overview: {
          productName: "TEMOFON Cork Footbed Sandals",
          sourceLabel: "amazon.com",
          statusLabel: "Elevated risk",
          riskScore: 74,
          manipulationProbability: 69,
          confidence: 92,
          reviewCount: 148,
          suspiciousCount: 34,
          manualReviewCount: 25,
          verdict:
            "The current review sample contains repeated sentiment patterns, clustered posting activity, and visible shifts in rating behavior.",
        },
        trustBreakdown: [
          { name: "Trustworthy", value: 89, fill: "#0f766e" },
          { name: "Suspicious", value: 34, fill: "#c35e43" },
          { name: "Uncertain", value: 25, fill: "#c4872f" },
        ],
        activitySeries: [
          { label: "Mon", reviews: 11, suspicious: 1 },
          { label: "Tue", reviews: 14, suspicious: 2 },
          { label: "Wed", reviews: 18, suspicious: 3 },
          { label: "Thu", reviews: 22, suspicious: 5 },
          { label: "Fri", reviews: 29, suspicious: 8 },
          { label: "Sat", reviews: 31, suspicious: 9 },
          { label: "Sun", reviews: 23, suspicious: 6 },
        ],
        anomalyTypes: [
          { type: "Text similarity", count: 14 },
          { type: "Burst posting", count: 11 },
          { type: "Temporal cluster", count: 9 },
          { type: "Bilingual slang signal", count: 8 },
          { type: "Rating shift", count: 7 },
          { type: "Sentiment repetition", count: 6 },
        ],
        detectorCards: [
          {
            id: "text-similarity",
            name: "Text Similarity Spike",
            description: "Multiple review bodies share nearly identical wording and promotional phrasing.",
            severity: "high",
            score: 82,
            status: "critical",
          },
          {
            id: "burst-posting",
            name: "Burst Posting Pattern",
            description: "A dense block of reviews arrived in a compressed time window.",
            severity: "high",
            score: 76,
            status: "critical",
          },
          {
            id: "reviewer-trust",
            name: "Reviewer Trust Anomaly",
            description: "A subset of visible reviewers contributes a disproportionate number of reviews.",
            severity: "medium",
            score: 63,
            status: "watch",
          },
          {
            id: "rating-distribution",
            name: "Rating Distribution Shift",
            description: "Extremely positive ratings dominate the latest cluster of visible reviews.",
            severity: "medium",
            score: 58,
            status: "watch",
          },
          {
            id: "sentiment-repetition",
            name: "Sentiment Repetition",
            description: "The language tone repeats the same emotional framing across different authors.",
            severity: "medium",
            score: 61,
            status: "watch",
          },
          {
            id: "bilingual-slang",
            name: "Bilingual Slang Check",
            description: "Mixed RU/EN slang shows up in a hype-heavy pattern instead of grounded customer detail.",
            severity: "medium",
            score: 59,
            status: "watch",
          },
          {
            id: "customer-photo-reuse",
            name: "Customer Photo Reuse",
            description: "Two reviews reuse the same customer-photo asset with different CDN query parameters.",
            severity: "medium",
            score: 64,
            status: "watch",
          },
          {
            id: "timed-photo-cluster",
            name: "Timed Photo Cluster",
            description: "The same image appears across different authors in a short window, suggesting a coordinated campaign.",
            severity: "high",
            score: 72,
            status: "watch",
          },
          {
            id: "image-text-alignment",
            name: "Photo vs Review Text",
            description: "CLIP/ViT similarity flags photos that weakly match the review text and product category.",
            severity: "medium",
            score: 67,
            status: "watch",
          },
          {
            id: "stock-marketing-photo",
            name: "Stock/Marketing Photos",
            description: "One photo signal looks closer to a catalog or studio asset than a customer snapshot.",
            severity: "medium",
            score: 62,
            status: "watch",
          },
          {
            id: "ai-synthetic-image",
            name: "AI/Synthetic Image Hint",
            description: "Weak synthetic-cue hint; not used as standalone proof.",
            severity: "low",
            score: 41,
            status: "stable",
          },
          {
            id: "image-ocr-text",
            name: "Photo OCR Text",
            description: "The photo contains sale/watermark/marketplace text that does not look like a normal customer snapshot.",
            severity: "medium",
            score: 57,
            status: "watch",
          },
          {
            id: "temporal-clustering",
            name: "Temporal Clustering",
            description: "Review timestamps form short-lived spikes instead of organic long-tail activity.",
            severity: "high",
            score: 79,
            status: "critical",
          },
        ],
        explainability: [
          {
            label: "High textual similarity across reviews",
            weight: 0.31,
            narrative: "The model found repeated lexical structures and near-duplicate phrases across multiple authors.",
          },
          {
            label: "Burst of reviews in a short interval",
            weight: 0.24,
            narrative: "Posting activity is compressed into a narrow time band, which is unusual for organic feedback.",
          },
          {
            label: "Low reviewer trust consistency",
            weight: 0.18,
            narrative: "Visible author behavior looks concentrated and less diverse than expected for a healthy product page.",
          },
          {
            label: "Rating distribution drift",
            weight: 0.16,
            narrative: "Recent ratings lean heavily toward the most extreme values, which amplifies manipulation risk.",
          },
          {
            label: "Repeated sentiment framing",
            weight: 0.11,
            narrative: "Several reviews reuse the same polarity and sales-style language rather than product-specific details.",
          },
        ],
        suspiciousReviews: [
          {
            id: "rvw-001",
            title: "Best purchase of the year",
            text: "Absolutely perfect, buy now, best purchase ever, every friend needs this immediately.",
            rating: 5,
            suspiciousness: 0.94,
            reason: "Promotional language + high text similarity",
            author: "TopPick247",
            authorTrust: "low",
            date: "2026-04-11",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["best purchase ever", "must buy", "fire"],
            languageSignalScore: 0.88,
            languageAuthenticityScore: 0.12,
            languageDomain: "apparel",
            templateClustered: true,
            uncertaintyScore: 0.12,
            oodScore: 0.08,
            imageUrls: ["https://cdn.example.test/reviews/sandal-fit-42.jpg?w=640&q=80"],
            imageCount: 1,
            duplicateImageCount: 1,
            duplicateImageClusterSize: 2,
            duplicateImageScore: 0.79,
            duplicateImageFlag: true,
            imageTemporalClusterScore: 0.66,
            imageTemporalClusterFlag: true,
            imageTemporalClusterSize: 2,
            imageTemporalClusterAuthorCount: 2,
            imageTemporalClusterWindowHours: 48,
            imageTextAlignmentScore: 0.22,
            imageTextMismatchScore: 0.71,
            imageTextMismatchFlag: true,
            imageTextAlignmentLabel: "strong_mismatch",
            imageStockMarketingScore: 0.68,
            imageStockMarketingFlag: true,
            imageStockMarketingLabel: "stock_catalog",
            imageSyntheticScore: 0.69,
            imageSyntheticFlag: true,
            imageSyntheticLabel: "weak_synthetic_hint",
            imageOcrScore: 0.62,
            imageOcrFlag: true,
            imageOcrText: "SALE BEST PRODUCT Amazon official store",
            imageOcrLabels: ["sale_discount", "hype_claim", "foreign_marketplace_watermark"],
          },
          {
            id: "rvw-002",
            title: "Five stars without a doubt",
            text: "Works amazing, flawless quality, must buy, 100 percent recommended to everyone.",
            rating: 5,
            suspiciousness: 0.88,
            reason: "Sentiment repetition + burst pattern",
            author: "dailydeal_mira",
            authorTrust: "low",
            date: "2026-04-11",
            severity: "high",
            triageStatus: "confident_suspicious",
            languageProfile: "suspicious",
            detectedTerms: ["fr", "must buy", "10/10 recommend"],
            languageSignalScore: 0.81,
            languageAuthenticityScore: 0.18,
            languageDomain: "apparel",
            templateClustered: true,
            uncertaintyScore: 0.18,
            oodScore: 0.12,
            imageUrls: ["https://cdn.example.test/reviews/sandal-fit-42.jpg?w=320&q=70"],
            imageCount: 1,
            duplicateImageCount: 1,
            duplicateImageClusterSize: 2,
            duplicateImageScore: 0.79,
            duplicateImageFlag: true,
            imageTemporalClusterScore: 0.66,
            imageTemporalClusterFlag: true,
            imageTemporalClusterSize: 2,
            imageTemporalClusterAuthorCount: 2,
            imageTemporalClusterWindowHours: 48,
          },
          {
            id: "rvw-003",
            title: "Really great item",
            text: "Great sandals, great fit, great quality, great comfort, great product overall.",
            rating: 5,
            suspiciousness: 0.82,
            reason: "Low lexical diversity",
            author: "comfortshopper",
            authorTrust: "neutral",
            date: "2026-04-10",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["great", "clean"],
            languageSignalScore: 0.43,
            languageAuthenticityScore: 0.54,
            languageDomain: "apparel",
            templateClustered: false,
            uncertaintyScore: 0.58,
            oodScore: 0.22,
            imageUrls: [],
            imageCount: 0,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
          {
            id: "rvw-004",
            title: "Short but perfect",
            text: "Perfect. Loved it. Must buy.",
            rating: 5,
            suspiciousness: 0.77,
            reason: "Extreme rating with generic explanation",
            author: "A1TopChoice",
            authorTrust: "low",
            date: "2026-04-10",
            severity: "medium",
            triageStatus: "needs_manual_review",
            languageProfile: "mixed",
            detectedTerms: ["must buy", "perfect"],
            languageSignalScore: 0.58,
            languageAuthenticityScore: 0.24,
            languageDomain: "apparel",
            templateClustered: false,
            uncertaintyScore: 0.62,
            oodScore: 0.31,
            imageUrls: ["https://cdn.example.test/reviews/sandal-box-single.jpg"],
            imageCount: 1,
            duplicateImageCount: 0,
            duplicateImageClusterSize: 0,
            duplicateImageScore: 0,
            duplicateImageFlag: false,
          },
        ],
        keyInsights: [
          "Review activity shows an abrupt late-stage spike.",
          "A concentrated subset of reviews mixes Russian and English slang in a promo-heavy tone.",
          "Detected a repeated emotional template across multiple authors.",
          "Reviewer concentration is higher than expected for this sample size.",
        ],
      };
}

function getSiteDataPreviewResult(locale: Locale): DashboardResult {
  const base = getHeroPreviewResult(locale);

  return {
    ...base,
    sourceMode: "records",
    overview: locale === "ru"
      ? {
          productName: "Platform Integrity Dataset",
          sourceLabel: "site-data",
          statusLabel: "Критический fraud-кластер",
          riskScore: 81,
          manipulationProbability: 78,
          confidence: 95,
          reviewCount: 420,
          suspiciousCount: 52,
          manualReviewCount: 0,
          verdict:
            "Структурированные site-data records показывают подозрительные user-кластеры, повторяющиеся IP и аномально насыщенное рейтинговое поведение, требующее модерации.",
        }
      : {
          productName: "Platform Integrity Dataset",
          sourceLabel: "site-data",
          statusLabel: "Critical fraud cluster",
          riskScore: 81,
          manipulationProbability: 78,
          confidence: 95,
          reviewCount: 420,
          suspiciousCount: 52,
          manualReviewCount: 0,
          verdict:
            "The structured site records reveal suspicious user clusters, repeated IP usage, and anomaly-heavy rating behavior that warrants moderation intervention.",
        },
  };
}

export function getDemoResult(mode: SourceMode, locale: Locale): DashboardResult {
  return mode === "records" ? getSiteDataPreviewResult(locale) : getHeroPreviewResult(locale);
}
